version: '3'

services:
  mongodb:
    image: mongo:4.0.6
    command: mongod
    ports:
      - "27017:27017"

  mongo-seed:
    build:
      context: .
      dockerfile: Dockerfile-mongoseed
    links:
      - mongodb
