version: '3'

services:
  mongo:
    image: mongo:4.0.6
    command: mongod
    ports:
      - "27017:27017"
    networks:
      - infra

  mongo-seed:
    build:
      context: mongo-seed
      dockerfile: Dockerfile
    depends_on:
      - mongo
    networks:
      - infra

  api:
    build:
      context: api
      dockerfile: Dockerfile
    environment:
      - MONGODB_URL=mongodb://mongo:27017/titanic
    ports:
      - "3000:3000"
    depends_on:
      - mongo-seed
    networks:
      - infra

networks:
  infra:
    driver: bridge
