version: '3'

services:
  mongodb:
    image: mongo:4.0.6
    command: mongod
    ports:
      - "27017:27017"
    networks:
      - infra

  mongo-seed:
    build:
      context: mongo-seed
      dockerfile: Dockerfile
    networks:
      - infra

networks:
  infra:
    driver: bridge
